from binarytree import *

B = BinaryTree()

bt_insert(B,"A",10)
bt_insert(B,"B",5)
bt_insert(B,"D",3)
bt_insert(B,"H",1)
bt_insert(B,"I",4)
bt_insert(B,"E",7)
bt_insert(B,"J",6)
bt_insert(B,"K",8)
bt_insert(B,"C",15)
bt_insert(B,"F",13)
bt_insert(B,"L",11)
bt_insert(B,"M",14)
bt_insert(B,"G",18)
bt_insert(B,"N",16)
print(bt_insert(B,"O",20))
print(bt_insert(B,"O",20))
print(bt_update(B,40,50))
print(bt_deleteKey(B,14))
#print(bt_delete(B, "A"))
print(bt_access(B, 8))
print(bt_update(B,50,4))
print(bt_access(B, 4))
bt_update(B,"I",4)
L = traverseInOrder(B)
L2 = traverseInPostOrder(B)
L3 = traverseInPreOrder(B)
imprimirlista(L)
print("")
imprimirlista(L2)
print("")
imprimirlista(L3)
print("")
L4 = traverseBreadFirst(B)
imprimirlista(L4)